### ISSUE TITLE
Connection just times out

### ISSUE THREAD

**Issue by morajabi** [LukeLambert/fly-dev-tunnel#1]
```
2021/03/03 10:50:17 [error] 536#536: *39 upstream timed out (110: Operation timed out) while connecting to upstream, client: 185.178.200.130, server: _.*, request: "GET / HTTP/1.1", upstream: "http://[fdaa:0:31:a7b:ab6:0:a:2]:7000/", host: "tunnel.fly.dev"
```

**Comment by LukeLambert** [comment]
Hmm. I'm also having some intermittent connection problems trying to recreate this issue. Can you try changing your WireGuard gateway? At the time of writing, `dev` was the only documented region, but now you can choose one closer to you. I'll update my project README to reflect that.

1. Find your existing peer name with `fly wireguard list`.
2. Delete it with `fly wireguard remove`.
2. List regions with `fly platform regions` and look for regions with a gateway checkmark.
3. Create a new WireGuard config with `fly wireguard create` and use the new region code:
    - Region: `ord`
    - DNS name: `mymacbook`
    - Filename: `fly.conf`
4. Open the WireGuard app, remove the old config, import the new config, and activate.
5. Redeploy your tunnel app with `fly deploy`.

That fixed any issues for me, but you also might want to double check that your `fly.toml` file has the correct environment variables:

```
[env]
  SUBDOMAINS = "_:7000"
  UPSTREAM = "mymacbook._peer.internal"
```

And check that your local webserver is:
1. Running on the specified port (7000, in your case).
2. Bound to `::`, which accepts connections for any IPv6 address.

Using Python 3, you can run a test webserver locally. Create a directory (or `cd` into one) with benign contents, as they will be public to the internet. Run `python3 -m http.server --bind :: 7000` to start a webserver serving the files in the current directory.
